"""FEDSIM Report API — composable PDF report builder."""
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import numpy as np


# Default strategy colors
STRATEGY_COLORS = {
    "FedAvg": "#d62728",
    "Krum": "#1f77b4",
    "Trimmed Mean": "#2ca02c",
    "Median": "#ff7f0e",
    "Reputation": "#9467bd",
    "FedProx": "#8c564b",
}


class Report:
    """Composable PDF report builder."""

    def __init__(self, title):
        self.title = title
        self._pages = []  # list of (type, kwargs) tuples

    def add_text(self, title, body):
        self._pages.append(("text", {"title": title, "body": body}))

    def add_convergence_plot(self, results, names, title="",
                              colors=None, strategy_idx=0):
        self._pages.append(("convergence", {
            "results": results, "names": names, "title": title,
            "colors": colors, "strategy_idx": strategy_idx,
        }))

    def add_accuracy_table(self, results, names=None, strategy_idx=0):
        self._pages.append(("table", {
            "results": results, "names": names, "strategy_idx": strategy_idx,
        }))

    def add_heatmap(self, data, row_labels, col_labels, title="", fmt=".3f"):
        self._pages.append(("heatmap", {
            "data": data, "row_labels": row_labels, "col_labels": col_labels,
            "title": title, "fmt": fmt,
        }))

    def save_pdf(self, path):
        with PdfPages(path) as pdf:
            # Title page
            fig = plt.figure(figsize=(11, 8.5))
            fig.text(0.5, 0.55, self.title, ha="center", va="center",
                     fontsize=24, fontweight="bold")
            fig.text(0.5, 0.42, "Generated by FEDSIM", ha="center",
                     va="center", fontsize=14, color="gray")
            pdf.savefig(fig, dpi=150, bbox_inches="tight")
            plt.close(fig)

            for page_type, kwargs in self._pages:
                if page_type == "text":
                    fig = self._render_text(**kwargs)
                elif page_type == "convergence":
                    fig = self._render_convergence(**kwargs)
                elif page_type == "table":
                    fig = self._render_table(**kwargs)
                elif page_type == "heatmap":
                    fig = self._render_heatmap(**kwargs)
                else:
                    continue
                pdf.savefig(fig)
                plt.close(fig)

    def _render_text(self, title, body):
        fig = plt.figure(figsize=(11, 8.5))
        fig.text(0.5, 0.92, title, ha="center", va="top",
                 fontsize=18, fontweight="bold")
        fig.text(0.1, 0.85, body, ha="left", va="top",
                 fontsize=11, wrap=True,
                 transform=fig.transFigure)
        return fig

    def _render_convergence(self, results, names, title, colors, strategy_idx):
        fig, (ax_loss, ax_acc) = plt.subplots(1, 2, figsize=(11, 5))
        fig.suptitle(title or "Convergence", fontsize=14, fontweight="bold")

        for i, name in enumerate(names):
            if name not in results:
                continue
            r_list = results[name]
            if strategy_idx >= len(r_list):
                continue
            r = r_list[strategy_idx]
            losses = r.round_losses if hasattr(r, 'round_losses') else r.get('round_losses', [])
            accs = r.round_accuracies if hasattr(r, 'round_accuracies') else r.get('round_accuracies', [])

            color = None
            if colors and name in colors:
                color = colors[name]
            else:
                # Auto-assign from default palette
                color = plt.cm.tab10(i / max(len(names), 1))

            label = name.split("/")[-1] if "/" in name else name
            ax_loss.plot(range(len(losses)), losses, label=label, color=color)
            ax_acc.plot(range(len(accs)), accs, label=label, color=color)

        ax_loss.set_xlabel("Round")
        ax_loss.set_ylabel("Loss")
        ax_loss.legend(fontsize=8)
        ax_loss.grid(True, alpha=0.3)

        ax_acc.set_xlabel("Round")
        ax_acc.set_ylabel("Accuracy")
        ax_acc.set_ylim(0, 1.05)
        ax_acc.legend(fontsize=8)
        ax_acc.grid(True, alpha=0.3)

        fig.tight_layout()
        return fig

    def _render_table(self, results, names, strategy_idx):
        if names is None:
            names = results.names
        rows = []
        for name in names:
            if name not in results:
                continue
            r_list = results[name]
            for si, r in enumerate(r_list):
                if strategy_idx is not None and si != strategy_idx:
                    continue
                accs = r.round_accuracies if hasattr(r, 'round_accuracies') else r.get('round_accuracies', [])
                losses = r.round_losses if hasattr(r, 'round_losses') else r.get('round_losses', [])
                strat = r.strategy_name if hasattr(r, 'strategy_name') else r.get('strategy_name', '?')
                rows.append({
                    "Run": name,
                    "Strategy": strat,
                    "Final Acc": f"{accs[-1]:.4f}" if accs else "N/A",
                    "Final Loss": f"{losses[-1]:.4f}" if losses else "N/A",
                    "Rounds": len(accs),
                })

        fig = plt.figure(figsize=(11, 8.5))
        fig.text(0.5, 0.95, "Results Summary", ha="center", fontsize=16, fontweight="bold")

        if not rows:
            fig.text(0.5, 0.5, "No results", ha="center", fontsize=14)
            return fig

        cols = list(rows[0].keys())
        cell_text = [[row[c] for c in cols] for row in rows]

        ax = fig.add_subplot(111)
        ax.axis("off")
        table = ax.table(cellText=cell_text, colLabels=cols, loc="center",
                         cellLoc="center")
        table.auto_set_font_size(False)
        table.set_fontsize(9)
        table.scale(1.0, 1.5)

        # Header styling
        for j in range(len(cols)):
            table[0, j].set_facecolor("#4472C4")
            table[0, j].set_text_props(color="white", fontweight="bold")

        return fig

    def _render_heatmap(self, data, row_labels, col_labels, title, fmt):
        fig, ax = plt.subplots(figsize=(11, 8.5))
        data_arr = np.array(data, dtype=float)
        im = ax.imshow(data_arr, cmap="RdYlGn", aspect="auto")

        ax.set_xticks(range(len(col_labels)))
        ax.set_xticklabels(col_labels)
        ax.set_yticks(range(len(row_labels)))
        ax.set_yticklabels(row_labels)

        # Annotate cells
        for i in range(len(row_labels)):
            for j in range(len(col_labels)):
                val = data_arr[i, j]
                text = f"{val:{fmt}}" if not np.isnan(val) else "N/A"
                # Use 40th percentile threshold for text contrast on RdYlGn colormap
                # (yellow midrange has high luminance → needs black text)
                _range = data_arr.max() - data_arr.min()
                _thresh = data_arr.min() + 0.4 * _range if _range > 0 else 0
                ax.text(j, i, text, ha="center", va="center", fontsize=10,
                        color="white" if val < _thresh else "black")

        ax.set_title(title or "Heatmap", fontsize=14, fontweight="bold")
        fig.colorbar(im, ax=ax, shrink=0.8)
        fig.tight_layout()
        return fig
